version: '3.7'
services:
  app:
    build:
      context: .
      target: dev-container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: mysql:host=db;dbname=promocode
      DB_USER: promocode
      DB_PASS: promocode
  db:
    image: mysql:8.0.34
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: secret
      DB_NAME: promocode
      MYSQL_USER: promocode
      MYSQL_PASSWORD: promocode
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-resources/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  tests:
    build:
      context: .
      target: dev-container
    restart: no
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    environment:
      DB_DSN: mysql:host=db;dbname=promocode_test
      DB_USER: promocode
      DB_PASS: promocode

volumes:
  db-data:
